# Generated by Django 3.2.3 on 2021-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.TextField(primary_key=True, serialize=False)),
                ('store_name', models.TextField()),
                ('store_phone_number', models.TextField(unique=True)),
                ('store_address', models.TextField()),
            ],
        ),
    ]
