# Generated by Django 3.2.3 on 2021-05-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
        ('store', '0002_userstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user_id',
            field=models.ForeignKey(default='q', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserStore',
        ),
    ]
