# Generated by Django 3.2.3 on 2021-05-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20210529_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemedicine',
            name='price',
            field=models.FloatField(),
        ),
    ]
