# Generated by Django 3.2.3 on 2021-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.TextField(primary_key=True, serialize=False)),
                ('role_type', models.TextField(unique=True)),
            ],
        ),
    ]
