# Generated by Django 3.2.3 on 2021-06-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_authorization_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='view_name',
            field=models.TextField(unique=True),
        ),
    ]
