# Generated by Django 3.2.3 on 2021-05-30 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 5, 30, 8, 8, 29, 707635, tzinfo=utc)),
        ),
    ]
